#!/usr/bin/perl
use strict;
use warnings;

use Term::ANSIColor qw(:constants);

my $sep = '--->';
my %definition;

while (<>) {
    chomp;
    my ( $expr, $def ) = split /\s*$sep\s*/;
    $definition{$expr} = $def;
}

my %count = ( wrong => 0, right => 0 );

for my $expr ( keys %definition ) {
    print BOLD, BLUE, $expr, RESET, " $sep ";
    chomp( my $ans = <STDIN> );
    if ( $ans eq $definition{$expr} ) {
        $count{right}++;
        print GREEN, "Right!\n", RESET;
    } else {
        $count{wrong}++;
        print "Not really, it's: '$definition{$expr}'\n";
    }
}

print "-" x 80, "\n";
print << "EOF";
Results:
[-] wrong: $count{wrong}
[+] right: $count{right}
EOF
